name: Actualizar VERING Mundial 2026
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Patch Campeones
        run: python3 patch_campeones.py

      - name: Generar HTML
        run: python3 build.py

      - name: Deploy a Netlify
        run: npx --yes netlify-cli deploy --prod --dir=./dist --auth=${{ secrets.NETLIFY_TOKEN }} --site=a6fe657d-d003-4e22-a624-b579f0541d08
